// <auto-generated />
using Departments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.SqlServer.Types;

#nullable disable

namespace Departments.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240720120415_SeedDepartmentsTable")]
    partial class SeedDepartmentsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Departments.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<SqlHierarchyId>("Path")
                        .HasColumnType("hierarchyid");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Root Department",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/")
                        },
                        new
                        {
                            Id = 2,
                            Name = "Department 01",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/")
                        },
                        new
                        {
                            Id = 3,
                            Name = "Department 02",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/2/")
                        },
                        new
                        {
                            Id = 4,
                            Name = "Department 03",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/")
                        },
                        new
                        {
                            Id = 5,
                            Name = "Department 04",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/")
                        },
                        new
                        {
                            Id = 6,
                            Name = "Department 05",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/5/")
                        },
                        new
                        {
                            Id = 7,
                            Name = "Department 06",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/1/")
                        },
                        new
                        {
                            Id = 8,
                            Name = "Department 07",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/2/")
                        },
                        new
                        {
                            Id = 9,
                            Name = "Department 08",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/3/")
                        },
                        new
                        {
                            Id = 10,
                            Name = "Department 09",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/4/")
                        },
                        new
                        {
                            Id = 11,
                            Name = "Department 10",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/5/")
                        },
                        new
                        {
                            Id = 12,
                            Name = "Department 11",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/1/")
                        },
                        new
                        {
                            Id = 13,
                            Name = "Department 12",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/2/")
                        },
                        new
                        {
                            Id = 14,
                            Name = "Department 13",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/1/")
                        },
                        new
                        {
                            Id = 15,
                            Name = "Department 14",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/1/1/")
                        },
                        new
                        {
                            Id = 16,
                            Name = "Department 15",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/3/1/")
                        },
                        new
                        {
                            Id = 17,
                            Name = "Department 16",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/5/1/")
                        },
                        new
                        {
                            Id = 18,
                            Name = "Department 17",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/2/1/")
                        },
                        new
                        {
                            Id = 19,
                            Name = "Department 18",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/2/2/")
                        },
                        new
                        {
                            Id = 20,
                            Name = "Department 19",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/1/1/")
                        },
                        new
                        {
                            Id = 21,
                            Name = "Department 20",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/1/2/")
                        },
                        new
                        {
                            Id = 22,
                            Name = "Department 21",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/1/3/")
                        },
                        new
                        {
                            Id = 23,
                            Name = "Department 22",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/3/1/1/")
                        },
                        new
                        {
                            Id = 24,
                            Name = "Department 23",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/5/1/1/")
                        },
                        new
                        {
                            Id = 25,
                            Name = "Department 24",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/2/1/1/")
                        },
                        new
                        {
                            Id = 26,
                            Name = "Department 25",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/2/1/2/")
                        },
                        new
                        {
                            Id = 27,
                            Name = "Department 26",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/2/1/3/")
                        },
                        new
                        {
                            Id = 28,
                            Name = "Department 27",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/1/2/1/")
                        },
                        new
                        {
                            Id = 29,
                            Name = "Department 28",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/1/3/1/")
                        },
                        new
                        {
                            Id = 30,
                            Name = "Department 29",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/2/1/1/1/")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
